# Generated by Django 4.1 on 2022-09-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_reddit_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.TextField()),
                ('comment_timestamp', models.TextField()),
                ('comment_body', models.TextField()),
                ('comment_upvotes', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
